# See https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap.toml for defaults

[mgr]
prepend_keymap = [
  # override 'q' shortcut to close current tab instead of quiting yazi
	{ on = "q", run = 'close', desc = "Close current tab, exit if one left" },
  # Dropping to the shell
	{ on = "!", run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
  # Drag and drop via dragon
  { on  = "<C-n>", run = ''' shell 'dragon -x -i -T "$1"' --confirm ''' },
  # Manage git repos with lazygit
  { on   = [ "g", "i" ], run  = "plugin lazygit", desc = "run lazygit" },
  # Compresses selected files to an archive
  { on   = [ "c", "a" ], run  = "plugin compress", desc = "Archive selected files" },
]
